services:

  postgres:
    image: pgvector/pgvector:pg15
    environment:
      POSTGRES_DB: erp
      POSTGRES_USER: erp
      POSTGRES_PASSWORD: erp
    ports:
      - "5432:5432"
    networks:
      - erp_corp_net
  redis:
    image: redis:7
    networks:
      - erp_corp_net

  backend:
    command: python manage.py runserver 0.0.0.0:8000
    build:
      context: .
      dockerfile: docker/Dockerfile
    volumes:
      - ./backend:/app
    ports:
      - "8000:8000"
    depends_on:
      - postgres
      - redis
    env_file:
      - .env
    networks:
      - erp_corp_net
  worker:
    build:
      context: .
      dockerfile: docker/Dockerfile
    command: celery -A core worker -l info
    volumes:
      - ./backend:/app
    depends_on:
      - redis
      - postgres
    env_file:
      - .env
    networks:
      - erp_corp_net
  celery-beat:
    build:
      context: .
      dockerfile: docker/Dockerfile
    command: celery -A core beat -l info
    volumes:
      - ./backend:/app
    depends_on:
      - redis
      - postgres
    env_file:
      - .env
    networks:
      - erp_corp_net      
  prometheus:
    image: prom/prometheus
    volumes:
      - ./docker/prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    networks:
      - erp_corp_net
  grafana:
    image: grafana/grafana
    ports:
      - "3000:3000"
    networks:
      - erp_corp_net

  embedding:
    build:
      context: .
      dockerfile: local_embedding/Dockerfile
    ports:
      - "5000:5000"
    networks:
      - erp_corp_net

  frontend:
    build:
      context: .
      dockerfile: ./frontend/Dockerfile
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app 
      - ./.node_modules:/home/node/.node_modules
    environment:
      - VITE_API_URL=http://localhost:8000/api
      - VITE_GRAFANA_URL=https://localhost:3000/
      - VITE_GITHUB_URL=https://github.com/fadi-c/erp_corp_ai_demo
    command: npm run dev -- --host
    networks:
      - erp_corp_net

networks:
  erp_corp_net:
    driver: bridge
