# Generated by Django 4.2 on 2026-03-07 16:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = []

    operations = [
        migrations.RunSQL(
            "CREATE EXTENSION IF NOT EXISTS vector;"
        )
    ]