# Generated by Django 4.2 on 2026-03-07 16:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("erp", "0002_initial")]

    operations = [
        migrations.RunSQL(
            """
            CREATE INDEX invoice_embedding_idx
            ON erp_invoiceembedding
            USING ivfflat (embedding vector_cosine_ops)
            WITH (lists = 100);
            """
        )
    ]
