global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'backend'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['backend:8000']

  - job_name: 'celery_worker'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['worker:5555']
  - job_name: celery_beat
    static_configs:
      - targets: ['celery-beat:5556']